# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RichPushNotificationsIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RichPushNotificationsIOS


# Add the Firebase pod for Google Analytics
#pod 'Firebase'
#pod 'Firebase/Core'
#pod 'Firebase/Messaging'
#pod 'Firebase/DynamicLinks'
#pod 'Firebase/Crashlytics'
#pod 'Firebase/Analytics'

# For Analytics without IDFA collection capability, use this pod instead
# pod ‘Firebase/AnalyticsWithoutAdIdSupport’

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
#pod 'Firebase/Auth'
#pod 'Firebase/Firestore'
#pod 'Firebase/Messaging'

#target 'RichPushNotificationsIOSService' do
##   use_frameworks!
##   pod 'Firebase'
#   pod 'Firebase/Messaging'
##   inherit! :search_paths
# end

end

#target 'RichPushNotificationsIOSService' do
#   use_frameworks!
##   pod 'Firebase'
#   pod 'Firebase/Messaging'
##   inherit! :search_paths
# end

target 'RichPushNotificationsIOSService' do
  use_frameworks!
  
#  pod 'Firebase/Messaging'
end
